import {useState,type CSSProperties} from 'react'
import {motion,AnimatePresence} from 'motion/react'
import {ArrowUpRight,Droplets,Plus,Minus,Download} from 'lucide-react'
import {useLocale} from '../lib/locale'
import {flavours,type Flavour} from '../lib/flavours'
import {ModelStage} from './ModelStage'
import {Eyebrow,Tilt} from './Primitives'

const shapes=[
 'M50 3 C83 0 101 27 96 54 C100 85 74 101 47 94 C13 106 0 76 6 48 C-2 19 23 8 50 3 Z',
 'M50 8 C74 -8 108 19 90 50 C109 81 78 109 50 89 C19 110 -8 77 10 50 C-7 23 21 -9 50 8 Z',
 'M50 2 C81 5 94 22 98 50 C90 78 85 95 50 98 C21 94 9 80 2 50 C8 21 24 5 50 2 Z',
 'M50 8 C97 -4 103 24 87 50 C103 80 80 100 50 93 C20 107 -3 78 12 50 C-4 21 19 -7 50 8 Z',
 'M50 2 C89 0 101 33 92 50 C104 83 65 99 50 97 C14 98 -2 74 8 50 C-2 24 22 2 50 2 Z',
 'M50 7 C83 -8 95 25 98 50 C98 82 70 105 50 90 C19 107 -5 73 7 50 C-8 16 23 -2 50 7 Z',
]
const flavorNotes:Record<Flavour,[string,string]>={blueberry_island:['A little berry. A whole new island.','توت أزرق. وعالم جديد من الانتعاش.'],original:['The original attitude. The unmistakable Twist.','الشخصية الأصلية. وطعم تويست اللي تعرفه.'],coconutberry:['Coconut meets berry. Your purple escape.','جوز الهند مع التوت. غيّر المود للبنفسجي.'],mango_peach:['Mango and peach. A tropical state of mind.','مانجو وخوخ. مزاج استوائي على طول.'],strawberry:['Strawberry red. Impossible to blend in.','أحمر الفراولة. حضور ما يتنسيش.'],power_craze:['A bold blue can with a cola twist.','أزرق جريء. وتويست بطعم الكولا.']}
export function MorphSection(){
 const [index,setIndex]=useState(2),{t,name,paused}=useLocale(),f=flavours[index]
 return <section id="mix" className="morph-section section-pad" data-section="6"><div className="morph-copy"><Eyebrow number="06">{t('CHANGE YOUR COLOR','غيّر لونك')}</Eyebrow><h2>{t('SAME TWIST.','نفس التويست.')}<br/><em>{t('NEW MOOD.','مزاج جديد.')}</em></h2><p>{t('A color for every side of you. Find the flavor that feels like today.','لكل جانب فيك لون. اختار النكهة اللي تشبه مزاجك النهارده.')}</p>
 <div className="color-picker" role="group" aria-label={t('Change flavor','غيّر النكهة')}>{flavours.map((item,i)=><button key={item.id} style={{'--swatch':item.color} as CSSProperties} onClick={()=>setIndex(i)} aria-label={name(item.id)} aria-pressed={i===index}><span/>{i===index&&<i/>}</button>)}</div>
 <AnimatePresence mode="wait"><motion.div key={f.id} initial={paused?false:{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} transition={{duration:.22}} className="flavor-note" aria-live="polite"><h3>{name(f.id)}</h3><p>{t(...flavorNotes[f.id])}</p></motion.div></AnimatePresence></div>
 <div className="morph-visual"><svg className="morph-blob" viewBox="-10 -10 120 120" aria-hidden="true"><motion.path animate={{d:shapes[index],fill:f.color,rotate:index*12}} transition={{duration:paused?0:1.2,ease:'easeInOut'}}/></svg><ModelStage mode="single" flavour={f.id} water="static" spin/></div></section>
}
const centers=[109,246,382,519,655,792]
export function TiltCollection({onPick}:{onPick:(f:Flavour)=>void}){
 const {t,name}=useLocale()
 return <section className="tilt-section section-pad" data-section="9"><div className="section-heading"><div><Eyebrow number="09">{t('THE PERSONALITY EDIT','كل نكهة بشخصية')}</Eyebrow><h2>{t('FIND YOUR','اختار')}<br/><em>{t('KIND OF BOLD.','اللي يشبهك.')}</em></h2></div><p>{t('Move a little closer. Every flavor has its own story.','قرّب شوية. كل نكهة وراها حكاية.')}</p></div>
 <div className="tilt-grid">{flavours.map((f,i)=><Tilt key={f.id} className="flavor-card" style={{'--accent':f.color,'--crop':centers[i]} as CSSProperties}><a href="#flavors" onClick={()=>onPick(f.id)} aria-label={`${t('Explore','استكشف')} ${name(f.id)}`}><div className="card-top"><span>0{i+1}</span><ArrowUpRight size={21} aria-hidden="true"/></div><div className="card-art"><img src="/media/all-six-front.png" alt={name(f.id)} loading="lazy"/></div><div className="card-bottom"><small>{f.id==='blueberry_island'?t('THE NEW DROP','النكهة الجديدة'):t('250 ML · TWIST ENERGY','٢٥٠ مل · تويست إنرجي')}</small><h3>{name(f.id)}</h3><span className="card-line"/></div></a></Tilt>)}</div></section>
}
export function WaterLab(){
 const {t,paused}=useLocale(),[wet,setWet]=useState(true),[density,setDensity]=useState(300)
 return <section className="water-section section-pad" id="chill" data-section="10"><div className="water-visual"><div className="water-ring"/><ModelStage mode="single" flavour="blueberry_island" water={wet?'animated':'off'} density={density} spin interactive/><span className="water-badge"><Droplets aria-hidden="true" size={17}/>{wet?t('FRESH OUT OF THE FRIDGE','لسه طالعة من التلاجة'):t('CLEAN & CLASSIC','بسيطة وكلاسيكية')}</span></div><div className="water-copy"><Eyebrow number="10">{t('THE CHILL FACTOR','درجة الانتعاش')}</Eyebrow><h2>{t('MAKE IT','خلّيها')}<br/><em>{t('ICE COLD.','ساقعة.')}</em></h2><p>{t('Tiny drops. A completely different feel. Turn up the chill and watch the water move.','قطرات صغيرة. وإحساس مختلف تمامًا. زوّد الانتعاش وشوف القطرات وهي بتتحرك.')}</p><button className="water-switch" role="switch" aria-checked={wet} onClick={()=>setWet(!wet)}><span>{t('Condensation','قطرات المياه')}</span><i data-on={wet}><b/></i></button><label className="density-control">{t('A little mist','رذاذ خفيف')}<span>{t('Extra chilled','برودة زيادة')}</span><input type="range" min="80" max="700" step="20" disabled={!wet} value={density} onChange={e=>setDensity(Number(e.target.value))} aria-label={t('Droplet density','كثافة القطرات')}/></label>{paused&&<p className="small-note">{t('Motion is paused. Droplets remain still.','الحركة متوقفة. القطرات ثابتة.')}</p>}</div></section>
}
export function OrbitSection(){const {t}=useLocale(),[spinning,setSpinning]=useState(true);return <section className="orbit-section section-pad" data-section="11"><Eyebrow number="11">{t('BETTER TOGETHER','مع بعض أحلى')}</Eyebrow><h2>{t('ALL IN THE','كلنا في')}<br/><em>{t('TWIST FAMILY.','عيلة تويست.')}</em></h2><ModelStage mode="orbit" flavour="all" water="off" spin={spinning} interactive/><button className="orbit-toggle" aria-pressed={spinning} onClick={()=>setSpinning(!spinning)}>{spinning?t('Pause the orbit','وقف الدوران'):t('Keep it moving','كمّل الدوران')}</button></section>}
export function FAQSection(){
 const {t}=useLocale(),[open,setOpen]=useState<number|null>(0)
 const items=[
 [t('Which flavors can I explore?','إيه النكهات الموجودة؟'),t('Original, Blueberry Island, Coconutberry, Mango Peach, Strawberry, and Power Craze. All six are available to rotate and inspect in the collection above.','أوريجينال، بلوبيري آيلاند، كوكونت بيري، مانجو خوخ، فراولة، وباور كريز. تقدر تلف وتشوف الست علب في المجموعة فوق.')],
 [t('What’s new about Blueberry Island?','إيه الجديد في بلوبيري آيلاند؟'),t('Blueberry Island is the newest flavor in this collection, with its signature baby-blue can and deep-blue accents.','بلوبيري آيلاند أحدث نكهة في المجموعة، بعلبتها الأزرق الفاتح وتفاصيلها بالأزرق الغامق.')],
 [t('Can I turn the animations off?','ممكن أقفل الحركة؟'),t('Yes. Use the motion button in the header. The site also respects your device’s reduced-motion setting. You can still select flavors and inspect each can.','أكيد. استخدم زر الحركة في أعلى الصفحة. الموقع كمان بيحترم إعداد تقليل الحركة في جهازك، وتقدر تختار النكهات وتشوف العلب عادي.')],
 [t('Where can I check product details?','أعرف تفاصيل المنتج منين؟'),t('Always check your physical can for ingredients, nutrition, and serving information. Packaging can vary by market and edition.','راجع العلبة اللي معاك لمعرفة المكونات والقيم الغذائية ومعلومات الاستخدام. شكل العبوة ومعلوماتها ممكن تختلف حسب السوق والإصدار.')],
 ]
 return <section className="faq-section section-pad" data-section="12"><div><Eyebrow number="12">{t('GOOD TO KNOW','معلومات تهمّك')}</Eyebrow><h2>{t('A LITTLE','تفاصيل')}<br/><em>{t('MORE TWIST.','عن تويست.')}</em></h2></div><div className="faq-list">{items.map(([q,a],i)=><article key={i}><h3><button aria-expanded={open===i} aria-controls={`faq-${i}`} onClick={()=>setOpen(open===i?null:i)}><span>{q}</span>{open===i?<Minus aria-hidden="true" size={21}/>:<Plus aria-hidden="true" size={21}/>}</button></h3><div id={`faq-${i}`} hidden={open!==i}><p>{a}</p></div></article>)}</div></section>
}
export function DownloadsSection(){const {t,name}=useLocale();return <section id="downloads" className="downloads-section section-pad" data-section="13"><div className="section-heading"><div><Eyebrow number="13">{t('THE CREATOR’S CORNER','ركن المبدعين')}</Eyebrow><h2>{t('TAKE THE','خُد')}<br/><em>{t('WHOLE COLLECTION.','المجموعة كلها.')}</em></h2></div><p>{t('Every flavor, front to back. Download your can with condensation or keep it clean.','كل نكهة، من كل ناحية. حمّل العلبة بقطرات المياه أو من غيرها.')}</p></div><a className="action bundle-download" href="/downloads/twist-all-six-models.zip" download><span>{t("Download all six · 12 GLBs", "حمّل الست نكهات · ١٢ ملف GLB")}</span><Download size={18} aria-hidden="true"/></a><div className="download-grid">{flavours.map((f,i)=><article key={f.id} style={{'--accent':f.color} as CSSProperties}><div className="download-title"><span>0{i+1}</span><h3>{name(f.id)}</h3></div><div><a href={`/models/${f.id}.glb`} download><Droplets size={16} aria-hidden="true"/>{t('Chilled GLB','GLB بقطرات')}<Download size={15} aria-hidden="true"/></a><a href={`/models/${f.id}_dry.glb`} download>{t('Dry GLB','GLB بدون قطرات')}<Download size={15} aria-hidden="true"/></a></div></article>)}</div></section>}
