import {useState,useRef,useEffect,lazy,Suspense} from 'react'
import {motion,MotionConfig} from 'motion/react'
import {ArrowDown,ArrowUpRight,Pause,Play,Menu,X} from 'lucide-react'
import {LocaleProvider,useLocale,type Language} from './lib/locale'
import {useSmoothScroll,useGSAP,gsap,ScrollTrigger} from './lib/motion'
import {ModelStage} from './components/ModelStage'
import {Eyebrow,Action} from './components/Primitives'
import {FlavorExplorer} from './components/FlavorExplorer'
import {FrostSection,BentoSection,WaypointSection} from './components/ScrollSections'
import {MorphSection,TiltCollection,WaterLab,OrbitSection,FAQSection,DownloadsSection} from './components/InteractiveSections'
import type {Flavour} from './lib/flavours'
const Onyx=lazy(()=>import('./components/ui/onyx-glyph-preloader'))
const bolt={d:'M57 5 L30 51 H48 L35 96 L74 38 H55 L72 5 Z',label:'Twist'}
const glyphs=[{d:'M18 23 H82 V38 H58 V83 H42 V38 H18 Z',label:'T'},{d:'M12 22 H28 L37 67 L44 35 H56 L64 67 L73 22 H89 L74 83 H57 L50 55 L43 83 H26 Z',label:'W'},bolt,{d:'M76 27 C60 9 25 16 23 39 C21 59 67 48 64 64 C62 75 39 72 27 62 L18 75 C35 95 78 89 81 65 C84 42 36 50 40 36 C42 26 62 29 67 36 Z',label:'S'},{d:'M18 23 H82 V38 H58 V83 H42 V38 H18 Z',label:'T'}]
function BrandIntro(){
 const {t,paused,heroReady}=useLocale()
 const introRef=useRef<HTMLDivElement>(null)
 const skipRef=useRef<HTMLButtonElement>(null)
 const [show,setShow]=useState(()=>{try{return !sessionStorage.getItem('twist-intro')&&!window.location.hash}catch{return false}})
 const close=()=>{if(introRef.current?.contains(document.activeElement))document.getElementById('main')?.focus({preventScroll:true});setShow(false);try{sessionStorage.setItem('twist-intro','1')}catch{}}
 useEffect(()=>{if(!show)return;const timer=setTimeout(close,900);return()=>clearTimeout(timer)},[show])
 useEffect(()=>{if(show&&!paused)skipRef.current?.focus({preventScroll:true})},[show,paused])
 if(!show||paused)return null
 return <div ref={introRef} className="brand-intro" role="dialog" aria-modal="true" aria-label={t('Welcome to Twist','أهلاً بيك في تويست')} onKeyDown={event=>{
   if(event.key==='Escape'){close();return}
   if(event.key!=='Tab')return
   const focusable=introRef.current?.querySelectorAll<HTMLElement>('button,[tabindex="0"]')
   if(!focusable?.length)return
   const first=focusable[0],last=focusable[focusable.length-1]
   if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}
   else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}
  }}><Suspense fallback={null}><Onyx glyphs={glyphs} mark={bolt} word="TWIST" caption={t('A new taste. A new mood.','طعم جديد. مزاج جديد.')} palette={{stage:'#081a33',metal:'#43859b',shade:'#102b47',rim:'#a1e4ed',glitter:'#d2f7ff',ink:'#e9ffff'}} progress={heroReady?100:0} durationMs={650} glitter={.45} onComplete={close} locale={t('en','ar')} fontFamily="'Barlow Condensed', 'Cairo Variable', sans-serif"/></Suspense><button ref={skipRef} onClick={close} className="skip-intro">{t('Skip intro','تخطّي المقدمة')}<ArrowUpRight size={17}/></button></div>
}
function Header(){const {t,language,setLanguage,paused,setPaused}=useLocale(),[open,setOpen]=useState(false);return <header className="site-header"><a className="brand" href="#home" aria-label={t('Twist home','الرئيسية تويست')}><img src="/twist-logo.svg" alt="TWIST"/><span>{t("EGYPT","مصر")}</span></a><nav className={open?'main-nav open':'main-nav'} aria-label={t('Main navigation','القائمة الرئيسية')}><a onClick={()=>setOpen(false)} href="#island">{t('The island','الآيلاند')}</a><a onClick={()=>setOpen(false)} href="#flavors">{t('Our flavors','نكهاتنا')}</a><a onClick={()=>setOpen(false)} href="#chill">{t('Get chilled','استمتع بالانتعاش')}</a></nav><div className="header-actions"><button className="language-button" onClick={()=>setLanguage(language==='en'?'ar':'en')} aria-label={language==='en'?'Switch to Arabic':'Switch to English'}>{language==='en'?'العربية':'EN'}</button><button className="motion-toggle" onClick={()=>setPaused(!paused)} aria-label={t(paused?'Resume motion':'Pause motion',paused?'تشغيل الحركة':'إيقاف الحركة')} aria-pressed={paused}>{paused?<Play size={16}/>:<Pause size={16}/>}</button><a className="nav-cta" href="#flavors">{t('Find your Twist','اختار تويست')}<ArrowUpRight aria-hidden="true" size={16}/></a><button className="menu-button" aria-expanded={open} aria-label={t('Toggle menu','افتح القائمة')} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header>}
function Hero(){const {t,paused}=useLocale();return <section id="home" className="hero" data-section="1"><div className="hero-grain"/><div className="hero-topline"><span className="new-pill"><i/>{t('THE NEW DROP','النكهة الجديدة')}</span><span>{t('TWIST ENERGY · 250 ML','تويست إنرجي · ٢٥٠ مل')}</span></div><div className="hero-title"><motion.h1 initial={paused?false:{y:55,opacity:0}} animate={{y:0,opacity:1}} transition={{duration:1,ease:[.2,.8,.2,1]}}>{t('BLUEBERRY','بلوبيري')}<br/><em>{t('ISLAND.','آيلاند.')}</em></motion.h1></div><div className="hero-model"><ModelStage mode="hero" water="animated" flavour="blueberry_island" spin/></div><div className="hero-copy"><span className="tiny">{t('A WHOLE NEW MOOD','مزاج جديد تمامًا')}</span><p>{t('Big berry energy.','طاقة بطعم التوت.')}<br/>{t('Your little escape.','رحلتك الصغيرة بعيد.')}<br/>{t('Meet Blueberry Island.','اكتشف بلوبيري آيلاند.')}</p><Action href="#flavors">{t('Explore the flavors','اكتشف النكهات')}</Action></div><div className="hero-bottom"><a href="#story"><ArrowDown size={17} aria-hidden="true"/>{t('SCROLL INTO THE ISLAND','انزل لعالم الآيلاند')}</a><span>01 — 13</span><span className="hero-bottom-note">{t('BABY BLUE. BOLD BY NATURE.','أزرق فاتح. بشخصية جريئة.')}</span></div></section>}
function Manifesto(){const root=useRef<HTMLElement>(null),{t,paused,language}=useLocale();const words=t('ORDINARY CAN WAIT. THERE’S A WHOLE ISLAND OF FLAVOR TO GET LOST IN.','العادي يستنّى. فيه عالم كامل من النكهات مستنيك تكتشفه.').split(' ');useGSAP(()=>{if(paused)return;gsap.fromTo('.manifesto-word',{opacity:.18},{opacity:1,stagger:.1,scrollTrigger:{trigger:root.current,start:'top 80%',end:'bottom 75%',scrub:1}})},{scope:root,dependencies:[paused,language],revertOnUpdate:true});return <section ref={root} id="story" className="manifesto section-pad" data-section="2"><Eyebrow number="02">{t('WELCOME TO YOUR OTHER SIDE','أهلاً بالجانب التاني منك')}</Eyebrow><h2>{words.map((word,i)=><span className="manifesto-word" key={i}>{word} </span>)}</h2><div className="manifesto-bottom"><span className="asterisk" aria-hidden="true">✳</span><p>{t('A fresh color. An unexpected flavor. A Twist on the everyday.','لون جديد. نكهة غير متوقعة. وتويست يغيّر يومك.')}</p><span className="tiny">{t('NOTHING ORDINARY HERE.','مفيش حاجة عادية هنا.')}</span></div></section>}
function DuoSection(){const {t}=useLocale();return <section className="duo-section section-pad" data-section="3"><div className="duo-copy"><Eyebrow number="03">{t('OUT OF THE ORDINARY','برا المألوف')}</Eyebrow><h2>{t('GOOD THINGS','الحلو')}<br/>{t('COME WITH','دايمًا معاه')}<br/><em>{t('A TWIST.','تويست.')}</em></h2><p>{t('Blueberry Island. A taste worth looking at twice.','بلوبيري آيلاند. طعم يستاهل تبص له مرتين.')}</p><Action href="#cold" light>{t('Break the ice','اكسر التلج')}</Action></div><div className="duo-model"><ModelStage mode="duo" water="static" spin/></div><span className="duo-stamp">{t("BLUE","أزرق")}<br/>{t("ON BLUE","في أزرق")}</span></section>}
function Footer(){const root=useRef<HTMLElement>(null),{t,paused,language}=useLocale();useGSAP(()=>{if(paused)return;gsap.fromTo('.footer-word',{y:100,scaleY:.72,transformOrigin:'center bottom'},{y:0,scaleY:1,ease:'elastic.out(1,.55)',duration:1.6,scrollTrigger:{trigger:root.current,start:'top 80%'}})},{scope:root,dependencies:[paused,language],revertOnUpdate:true});return <footer ref={root} className="site-footer"><div className="footer-top"><span>{t('THAT’S YOUR CUE.','دي إشارتك.')}</span><a href="#home">{t('Back to the island','ارجع للآيلاند')}<ArrowUpRight size={18} aria-hidden="true"/></a></div><a className="footer-word" href="#flavors" aria-label={t('Explore Twist flavors','اكتشف نكهات تويست')}><img src="/twist-logo.svg" alt="TWIST"/><span aria-hidden="true">↗</span></a><div className="footer-bottom"><span>{t('A NEW TASTE. A NEW MOOD.','طعم جديد. مزاج جديد.')}</span><div><a href="#flavors">{t('Flavors','النكهات')}</a><a href="#downloads">{t('3D collection','المجموعة المجسمة')}</a></div><small>{t('Independent concept · Egypt · 2026','تصوّر تصميمي مستقل · مصر · ٢٠٢٦')}</small></div></footer>}
function Site(){const {paused,language,t}=useLocale(),[selected,setSelected]=useState<Flavour|'all'>('all');useSmoothScroll(paused);useEffect(()=>{const id=setTimeout(()=>ScrollTrigger.refresh(),350);return()=>clearTimeout(id)},[language,paused]);return <MotionConfig reducedMotion={paused?'always':'user'}><div className={paused?'site motion-paused':'site'}><a className="skip-link" href="#main">{t('Skip to content','انتقل للمحتوى')}</a><Header/><main id="main" tabIndex={-1}><Hero/><Manifesto/><DuoSection/><FrostSection/><FlavorExplorer selected={selected} onSelect={setSelected}/><MorphSection/><BentoSection/><WaypointSection/><TiltCollection onPick={setSelected}/><WaterLab/><OrbitSection/><FAQSection/><DownloadsSection/></main><Footer/><BrandIntro/></div></MotionConfig>}
export default function App({initialLanguage}:{initialLanguage?:Language}={}){return <LocaleProvider initialLanguage={initialLanguage}><Site/></LocaleProvider>}
