import React from 'react'
import {createRoot} from 'react-dom/client'
import App from './App'
import '@fontsource/barlow-condensed/latin-600.css'
import '@fontsource/barlow-condensed/latin-700.css'
import '@fontsource/barlow-condensed/latin-800-italic.css'
import '@fontsource-variable/cairo'
import 'lenis/dist/lenis.css'
import './style.css'
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
